### ISSUE TITLE
Support of fermionic systems

### ISSUE THREAD

**Issue by diret47** [ITensor/PEPS.jl#12]
Hi, developers.
Is it possible to compute fermionic PEPS with `ITensor`? For example Hubbard model?

**Comment by emstoudenmire** [comment]
Hi, this package PEPS.jl is no longer supported and is here for historical purposes only. We are currently working on some other tools for studying fermionic systems with PEPS using ITensor, but they are not ready to be released yet. When they are, they will be associated with the (unreleased but publicly viewable) ITensorNetworks.jl package.

**Comment by emstoudenmire** [comment]
If you have further questions about the ITensor ecosystem, please post them at our forum at https://itensor.discourse.group. And please reserve Github Issues for bug reports or feature requests. Thanks.
