### ISSUE TITLE
PEPS.jl and peps.jl file overwriting each other

### ISSUE THREAD

**Issue by emstoudenmire** [ITensor/PEPS.jl#2]
On my Mac system, the presence of two files which have an identical name up to capitalization is causing a problem where git overwrites one with another. (It warned about this when I first cloned the repo.) Could the peps.jl file be renamed to something distinct, such as peps_util.jl or similar?

**Comment by kshyatt** [comment]
Sure - shows what you get for only testing this on Linux :p

**Comment by kshyatt** [comment]
Renamed - can you confirm this fixed the problem? Thanks for pointing this out.

**Comment by emstoudenmire** [comment]
Fixes the problem - thanks!
